quantum-compiler/quartz

src/quartz/dag/dag.cpp, src/quartz/dag/dag.h, src/quartz/generator/generator.cpp, src/quartz/generator/generator.h, src/quartz/utils/utils.h, src/test/test_bfs.cpp, src/test/test_generator.cpp, src/test/test_generator.h, src/test/test_phase_shift.cpp, src/test/test_pruning.cpp, src/test/test_pruning.h, src/test/test_sparsity.cpp
This PR adds an argument `unique_parameters` to `generate()` and `test_pruning()`. If `unique_parameters` is true, then we only search for circuits that use each input parameter only once (note that doubling a parameter is not considered as using twice). So we will search for circuits using parameters like `p1, 2p2`, `p1 + p2, p3`, but not `p1, p1 + p2`.
Setting `unique_parameters=false` will make the behavior the same as before.
=> Enforce each input parameter to be used only once

src/quartz/dag/dag.cpp, src/quartz/dag/dag.h, src/quartz/dataset/dataset.cpp, src/quartz/dataset/dataset.h, src/quartz/dataset/equivalence_set.cpp, src/quartz/dataset/equivalence_set.h, src/quartz/gate/gate.cpp, src/quartz/gate/gate.h, src/quartz/generator/generator.cpp, src/quartz/generator/generator.h, src/quartz/verifier/verifier.cpp, src/test/test_all.cpp, src/test/test_generator.h, src/test/test_sparsity.cpp
This PR changes the `generator.cpp` to generate the gates in the order of qubit indices, and the `verifier.cpp` to check if canonicalize(dropfirst) is a representative.
It also changes the code format of several relevant files to make the tab size to be 2 spaces so each line will not be too long.
The size of ECC sets, including the number of ECCs, the number of circuits, and the number of transformations, will be slightly changed due to a different selection of representatives.
=> [Generator] Use canonical sequence representation for RepGen

src/quartz/dag/dag.cpp, src/quartz/dag/daghyperedge.cpp, src/quartz/dag/daghyperedge.h, src/quartz/generator/generator.cpp, src/quartz/verifier/verifier.cpp
Logs when generating (3,3)- and (4,3)-complete ECC sets for the Nam gate set on an Ubuntu workstation:
```
Nam_3_3 generated. Running Time (s): 5.301
Pruning Time (s): 0.054
Verification Time (s): 4.461
Num_total_dags = 193, num_equivalence_classes = 81
*** Number of transformations of Nam_3_3 = 224
Nam_4_3 generated. Running Time (s): 41.493
Pruning Time (s): 0.453
Verification Time (s): 32.829
Num_total_dags = 1294, num_equivalence_classes = 588
*** Number of transformations of Nam_4_3 = 1412
```
=> [Generator] Minor optimization on generator based on canonical representation

src/benchmark/nam_small_circuits.cpp, src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h
This PR mainly adds a function to compute the circuit depth. @zikun-li Please review it :)
This PR doesn't change the default cost function (which is gate count).
Benchmark `nam_small_circuits`:
If we use gate count as the cost function:
```
tof_3 after toffoli flip in 0.04 seconds: gate count = 39, circuit depth = 31, cost = 39
tof_3: bestCost(39.0000) candidates(0) after 0.0000 seconds
tof_3: bestCost(37.0000) candidates(1) after 3.8360 seconds
tof_3: bestCost(35.0000) candidates(1) after 6.1590 seconds
tof_3: bestCost(35.0000) candidates(0) after 7.9390 seconds
tof_3 optimization result in 11.051 seconds: gate count = 35, circuit depth = 31, cost = 35
barenco_tof_3 after toffoli flip in 0.043 seconds: gate count = 46, circuit depth = 41, cost = 46
barenco_tof_3: bestCost(46.0000) …
```
=> [Optimizer] Add an option to optimize for circuit depth

src/benchmark/nam_small_circuits.cpp
This PR is to make the small benchmark more consistent with the paper. The results do not change.
Before (on an Ubuntu workstation):
```
tof_3 after toffoli flip in 0.004 seconds: gate count = 39, cost = 39
tof_3: bestCost(39.0000) candidates(0) after 0.0000 seconds
tof_3: bestCost(37.0000) candidates(1) after 0.3010 seconds
tof_3: bestCost(35.0000) candidates(1) after 0.5530 seconds
tof_3: bestCost(35.0000) candidates(0) after 0.7500 seconds
tof_3 optimization result in 1.113 seconds: gate count = 35, cost = 35
barenco_tof_3 after toffoli flip in 0.006 seconds: gate count = 46, cost = 46
barenco_tof_3: bestCost(46.0000) candidates(0) after 0.0000 seconds
barenco_tof_3: bestCost(44.0000) candidates(3) after 0.4730 seconds
barenco_tof_3: bestCost(42.0000) candidates(5) after 0.8790 seconds …
```
=> [Benchmark] Change alpha from 0.999 to 1.0001 in the benchmark

README.md, src/benchmark/nam_small_circuits.cpp, src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h, src/test/test_ibmq.cpp, src/test/test_ibmq_td_disabled.cpp, src/test/test_nam.cpp, src/test/test_nam_td_disabled.cpp, src/test/test_optimization.h, src/test/test_quartz.cpp, src/test/test_rigetti.cpp, src/test/test_rigetti_td_disabled.cpp
This PR refactors the codebase to use the new `optimize` function in all cases, and rename the old one to be `optimize_legacy`.
It also creates a `optimize` function to take as input the ECC set file name and call the new `optimize` function for easier invocation.
It also adds a short summary for `src/benchmark/nam_small_circuits.cpp` for it to be easier to read.
It also changes the default timeout from 1 day to 1 hour.
Benchmark on Ubuntu workstation:
Before this PR:
```
tof_3 optimization result in 10.277 seconds: gate count = 35, cost = 35
barenco_tof_3 optimization result in 10.381 seconds: gate count = 40, cost = 40
mod_mult_55 optimization result in 10.849 seconds: gate count = 97, cost = 97
vbe_adder_3 optimization result in 10.977 seconds: gate count = 109, cost = 109
gf2^4_mult …
```
=> [Refactor] Use the new optimize function

src/benchmark/nam_small_circuits.cpp, src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h, src/test/test_optimize.cpp
Related PR = https://github.com/quantum-compiler/quartz/pull/37#issuecomment-1204384289
This PR makes the `optimize` function check in each iteration if the size of the candidate queue is more than 2000. If so, shrink it to 1000 to avoid consuming too much memory.
Also prints the log into a file in `optimize`.
=> [Optimizer] Set the candidate queue capacity to 2000

src/benchmark/nam_small_circuits.cpp, src/quartz/dag/dag.cpp, src/quartz/dag/dag.h, src/quartz/tasograph/tasograph.cpp
This PR changes the `xfers` in 
```c++
std::shared_ptr<Graph> optimize(Context *ctx,
const std::string &equiv_file_name,
const std::string &circuit_name,
bool print_message,
std::function<float(Graph *)> cost_function = nullptr,
double cost_upper_bound = -1 /*default = current cost * 1.05*/,
int timeout = 3600 /*1 hour*/);
```
to be only the circuit transformations involving the representative circuit.
Note that you can still specify the `xfer` set by calling the function
```c++
std::shared_ptr<Graph> optimize(const std::vector<GraphXfer *> &xfers,
double cost_upper_bound,
const std::string &circuit_name,
const std::string &log_file_name,
bool print_message,
std::function<float(Graph *)> cost_function = nullptr,
int timeout = 3600 /*1 hour*/);
```
The nam_small_benchmark on laptop now: …
=> [Optimizer] Reduce the number of xfers in optimize()

experiment/ppo-new/actor.py, experiment/ppo-new/config/base_config.py, experiment/ppo-new/ds.py, experiment/ppo-new/model/actor_critic.py, experiment/ppo-new/ppo.py
1. fix: `next_nodes` information may be wrong.
2. feat: enable k-hop subgraph optimization by default, which only collects k-hop subgraph (in DGL) for training.
=> k-hop subgraph optimization for PPO

src/benchmark/CMakeLists.txt, src/benchmark/nam_middle_circuits.cpp, src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h
This PR prepends a preprocessing pass to the `optimize()` function -- the `greedy_optimize()` pass.
This pass greedily transforms the circuit towards lower cost (by default when the cost function is the gate count, this function greedily transforms the circuit towards fewer gates).
To show the effectiveness of this pass, I added a benchmark for middle-sized circuits (450-900 gates in the benchmark). (There is no significant difference in the current small benchmark.) Before this PR, the output of the middle-sized-circuit benchmark is:
```
barenco_tof_10 after toffoli flip in 0.113 seconds: gate count = 326, circuit depth = 282, cost = 326
Number of xfers: 62287
Timeout. Program terminated. Best cost is 323
barenco_tof_10 optimization result in 11.065 seconds: gate count = 323, circuit …
```
=> [Optimizer] Add a preprocessing pass to greedily optimize the circuit and add a benchmark

README.md, src/benchmark/nam_middle_circuits.cpp, src/benchmark/nam_small_circuits.cpp, src/quartz/dataset/equivalence_set.cpp, src/quartz/dataset/equivalence_set.h, src/quartz/dataset/representative_set.cpp, src/quartz/dataset/representative_set.h, src/test/gen_ecc_set.cpp, src/test/gen_ecc_set.h
This PR adds a parameter in `gen_ecc_set()` to output the representative set besides the ECC set or not.
If `generate_representative_set = true`, `gen_ecc_set()` will output a file with name like `Nam_4_3_representative_set.json` besides `Nam_4_3_complete_ECC_set.json`.
=> [Generator] Output the representative set

src/quartz/dataset/equivalence_set.cpp
This PR sorts each ECC when loading the ECC set. If we don't do this, when 2 ECCs are merged together in the Python verifier, there is no guarantee that the ECC with the lexicographically smaller representative will appear first, so the new representative might be not maintained to still be the smallest one in the ECC. Simply sorting the ECC will solve this problem.
=> [bug] Sort each ECC when loading the ECC set

src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/dataset/dataset.cpp, src/quartz/dataset/dataset.h, src/quartz/dataset/equivalence_set.cpp, src/quartz/generator/generator.cpp, src/quartz/generator/generator.h, src/quartz/verifier/verifier.cpp, src/test/gen_ecc_set.h, src/test/test_generator.h, src/test/test_phase_shift.cpp, src/test/test_pruning.h
This PR renames the parameter `verify_equivalences` of `generate()` to `invoke_python_verifier` as a switch to invoke the Python verifier or not. When this is `true`, the behavior is exactly the same as before this PR.
When `invoke_python_verifier` is `false`, Quartz will not invoke the Python verifier which verifies all equivalences by Z3. Instead, it treats circuits with hash values differing no more than 1 as equivalent.
When there are no parameters in the circuits, as long as two circuits' hash values are very close to each other, even if they are actually not equivalent, it is guaranteed that their matrices will not differ much. So it is considered safe to not invoke the Python verifier (which will accelerate the generation time by a lot) in this case.
=> [Generator] Do not invoke the Python verifier by default when no parameters

src/quartz/context/rule_parser.h, src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/quartz/utils/utils.h
Related issue = #59
This PR lets `QASMParser` support multiple quantum registers. The qubit indices will be ordered according to the alphabetical order of quantum registers, for example, in the following QASM,
```qasm
qreg q[2];
qreg p[1];
qreg q0[1];
```
qubits `0, 1, 2, 3` will correspond to `p[0], q[0], q[1], q0[0]`.
I think if we want to implement a QASM parser on our own, we should implement in `QASMParser` which natively creates a `CircuitSeq`, because the sequence representation is more similar to QASM (than the graph representation is).
=> [QASM] Support multiple quantum registers

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/parser/qasm_parser.h
A follow-up of #63.
Now we can call `CircuitSeq::from_qasm_file` like `Graph::from_qasm_file`.
=> [qasm] Add CircuitSeq::from_qasm_file()

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h
This PR adds support to the format `0.123/(2*pi)`, which appears in one circuit in the simulation branch.
Maybe we should switch to a systematic parameter evaluator...
=> [qasm] Add one kind of parameter format support in QASM parser

src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitgate.h, src/quartz/gate/ccx.h, src/quartz/gate/ccz.h, src/quartz/gate/ch.h, src/quartz/gate/cp.h, src/quartz/gate/cx.h, src/quartz/gate/cz.h, src/quartz/gate/gate.cpp, src/quartz/gate/gate.h
This PR adds support functions `Gate::get_num_control_qubits()`, `CircuitGate::get_qubit_indices()`, `CircuitGate::get_control_qubit_indices()`.
=> [gate] Add some support functions for controlled gates

src/python/simulator/ilp.py, src/test/test_simulation.cpp
This PR minimizes the number of swaps between iterations in the ILP.
However, it causes the current DP result to be much worse. Because there is only 1 global qubit in the current benchmark circuit, I think this is probably random.
Before this PR, test_simulation runs 541 seconds on my laptop and the costs are 295.8+319=614.8.
After this PR, test_simulation runs 4496 seconds on my laptop and the costs are 1364+10.4=1374.4.
This is probably because the second iteration after this PR contains only 1 gate:
```
CircuitSeq {
Q0 = h(Q0)
[Q0, Q28] = swap(Q0, Q28)
}
```
and the first iteration is setting qubit 0 as the global qubit. In this way, there are a lot of partially global sparse gates (e.g., `cp(Q10, Q0)`) in the first iteration, and they're not cost-efficient in the current DP.
=> [simulation] Add the s array to ILP and print the running time in test_simulation

src/python/simulator/ilp.py, src/quartz/simulator/schedule.cpp
This PR fixes the bug of the DP not considering "global" gates. The ILP could output fewer than k local qubits before this PR, but we don't have enough devices to support more than n-k global qubits. This PR simply fixes the bug by enforcing the ILP to output exactly k local qubits.
It also fixes a bug introduced in https://github.com/quantum-compiler/quartz/commit/e0f0c961d9e199f8ee9a0b1411909f94f19f69fd which caused `Schedule::compute_end_schedule()` to not compute the cost accurately when the `result_kernels` parameter is `nullptr`.
It also changes
```c++
constexpr int kMaxNumOfStatus = 10000;
constexpr int kShrinkToNumOfStatus = 5000;
```
to
```c++
constexpr int kMaxNumOfStatus = 4000;
constexpr int kShrinkToNumOfStatus = 2000;
```
to reduce the running time.
After these changes,
- …
=> [simulation] Fix a bug about ILP and DP

src/quartz/simulator/kernel.cpp, src/quartz/simulator/kernel.h, src/quartz/simulator/kernel_cost.cpp, src/quartz/simulator/kernel_cost.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/test/test_simulation.cpp
Also fixes a bug introduced in #78 that caused some single-qubit gates to be not executed.
Benchmark: `test_simulation`, `qft` circuit, 31 total qubits, 28 local qubits.
- Before this PR: 25 + 123 = 148 kernels, total cost = 275 + 1351.8 = 1626.8, running time = 53s
- After this PR with max shared-memory kernel size = 7: 22 + 117 = 139 kernels, total cost = 253 + 1371.6 = 1624.6
- After this PR with max shared-memory kernel size = 8: 5 + 50 = 55 kernels, total cost = 82.8 + 364 = 446.8, running time = 42s
For `dj` circuit with 31 total qubits and 28 local qubits, we get 4 + 1 = 5 kernels and total cost = 78 + 11 = 89 now.
=> [Simulation] DP for shared-memory gates

src/python/simulator/ilp.py, src/quartz/gate/ccz.h, src/quartz/gate/cp.h, src/quartz/gate/cz.h, src/quartz/gate/gate.h, src/quartz/gate/swap.h, src/quartz/pybind/pybind.cpp, src/quartz/pybind/pybind.h, src/quartz/simulator/schedule.cpp
Previously, we treated a gate as executable as long as it is "sparse" (a permutation matrix times a diagonal matrix).
But this is not true for the CX gate: the gate is only executable when the target qubit is local.
Now the logic becomes:
- For controlled gates, we need the target qubit to be local when and only when the gate is not *symmetric* (i.e., every qubit can be a control qubit).
- For non-controlled gates, we need all qubits to be local when it is a "dense" gate (single-qubit gates with at least 3 non-zero entries in the matrix, and possibly all non-controlled multi-qubit gates except for the SWAP gate).
=> [simulation] Fix CX in execution schedules when the target is global

src/quartz/circuitseq/circuitseq.cpp
When it is not a simple clone (without any permutations), we cannot copy the hash value because the circuits are different.
=> [bug] Fix clone_from() copying hash value incorrectly

src/python/simulator/ilp.py, src/quartz/simulator/schedule.cpp
A follow-up of #82.
`SWAP` gate is not executable when one qubit is global and the other is local.
=> [simulation] Restrict the Swap gate as local-only

src/python/simulator/ilp.py, src/quartz/simulator/kernel_cost.cpp, src/quartz/simulator/kernel_cost.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/test/test_simulation.cpp
A follow-up of #80. Changes `Schedule::local_qubit_` from `std::vector<bool>` to `std::vector<int>`, and it is now assumed that the least significant bit is placed in `local_qubit_[0]`; the ILP outputs qubit indices in ascending order now, so the qubit with the lowest index will always be considered as the least significant bit.
Benchmark: test_simulation, qft circuit, 31 total qubits, 28 local qubits, max shared-memory kernel size=11, shared-memory cacheline size=3.
Before: 42 + 10 = 52 kernels, total cost = 322.2 + 114.4 = 436.6, running time = 24s
After: 42 + 9 = 51 kernels, total cost = 322.2 + 113.8 = 436, running time = 24s
=> [simulation] Consider cacheline qubits in DP for shared-memory kernels

src/quartz/dataset/equivalence_set.cpp, src/quartz/dataset/equivalence_set.h
A new ECC class pruning pass `EquivalenceSet::remove_qubit_permutations` is implemented, which eliminate redundant `EquivalenceClass` that are equivalent up to some permutations of the qubits.
=> Ecc pruning dev

src/quartz/gate/u3.h
the upper right element should contain a minus sign, which was missing from `u3.h` but is present in the `u3` implementation in `src/python/verifier/gates.py`
=> fix u3 matrix implementation

src/quartz/simulator/schedule.cpp
Fix #89 
Fixes a bug introduced in #78 causing non-executable global single-qubit gates to be placed in kernels.
=> [simulation] Fix non-executable global gates in kernels

src/quartz/gate/ccz.h, src/quartz/gate/cp.h, src/quartz/gate/cu1.h, src/quartz/gate/cz.h, src/quartz/gate/gate.cpp, src/quartz/gate/gate.h, src/quartz/gate/p.h, src/quartz/gate/pdg.h, src/quartz/gate/s.h, src/quartz/gate/sdg.h, src/quartz/gate/t.h, src/quartz/gate/tdg.h, src/quartz/gate/u1.h, src/quartz/gate/z.h, src/quartz/simulator/schedule.cpp
The ultimate goal for this PR is to make the DP only require target qubits to be active in shared-memory kernels for controlled gates, and not require any qubit to be active for gates with diagonal matrices (e.g., Z, CZ, P, CP).
This PR modifies the absorbing kernel optimization part to adapt it, and also the greedy execution part. Therefore (because it didn't modify the DP transition), the final schedule could be much better than what the DP algorithm anticipated, and there can be many empty kernels.
Benchmark: test_simulation, qft circuit, 31 total qubits, 28 local qubits, max shared-memory kernel size=10, shared-memory cacheline size=3.
Before: 42 + 10 = 52 kernels (2 fusion, 50 shared-memory), total cost = 733.6 + 192.4 = 926, running time = 29s
After: 9 + 9 = 18 kernels (2 fusion, 16 …
=> [simulation] Only require target qubits to be active in shared-memory kernels (stage 1)

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/simulator/kernel.cpp, src/quartz/simulator/kernel.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
A follow-up of #97.
Changes:
- The DP status is now a product of 2 lists `vector<KernelInDP> open_kernels` and `vector<KernelInDP> absorbing_kernels`, where `KernelInDP` is a tuple of `vector<int> active_qubits`, `vector<int> touching_qubits`, and `KernelType tp`.
- When `tp` is `fusion`, the set `touching_qubits` is always empty for now. A qubit can appear in multiple `touching_qubits`, but if a qubit appears in one `active_qubits`, it cannot appear in any other `active_qubits` or `touching_qubits`.
- You can think of it as a status of operations with no data dependencies where `active_qubits` is a write operation and `touching_qubits` is a read operation.
- `KernelInDP` is sorted by the first active qubit. Kernels with no active qubits are placed after kernels with some active qubits; …
=> [simulation] Only require target qubits to be active in shared-memory kernels (stage 2)

src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitgate.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
Fixes the issue about the wrong simulation result mentioned in #99.
Changes:
- Adds functions `CircuitGate::get_insular_qubit_indices()` and `CircuitGate::get_non_insular_qubit_indices()`.
- Prints error message if the circuit is not entangled (i.e., there is one qubit with only single-qubit gates on it) in the function `get_schedules()`.
- Before feeding the circuit sequence to the DP, we now arrange a multi-qubit gate for each single-qubit gate, and update the non-insular qubits for these multi-qubit gates accordingly. Note that here "multi-qubit gate" and "single-qubit gate" are distinguished by the number of local qubits.
- Renames `absorb_single_qubit_gates` to `attach_single_qubit_gates` because we are now attaching these gates which may have side effects (updating the non-insular …
=> [simulation] Attach single-qubit gates to multi-qubit gates before DP

src/quartz/simulator/schedule.cpp, src/test/test_simulation.cpp
Changes:
- Fixes the bug when greedily executing the kernels after the DP, we might execute multi-qubit gates with a non-insular qubit before executing a previous multi-qubit gate with the same qubit as an insular qubit before this PR.
- When closing shared-memory kernels, we now add as many `touching_qubits` as possible, instead of sticking to the existing `touching_qubits`. However, we still do not remove existing absorbing kernels, although it may be better to remove some existing absorbing kernels' `active_qubits` in exchange for more `touching_qubits` in the new absorbing kernel.
TODOs:
- We still have empty kernels in `realamprandom`.
- We may want to update the cost for each gate based on the single-qubit gates attached to it.
- Do we want to try removing some existing absorbing …
=> [simulation] Bug fixes about executing gates in the DP

src/python/simulator/ilp.py
Previously the ILP outputs qubits in alphabetical order on `string(int)` for the first stage.
Now we sort it to be simply an increasing order.
=> [simulation] Sort the qubits in ILP

src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
A follow-up of #100 and #102.
Benchmark: `realamprandom`, 28 total qubits, 28 local qubits
Before: 22 kernels (1 fusion (0 non-empty), 21 shared-memory (20 non-empty)), cost = 1125.8, running time = 34s
After: 22 kernels (1 fusion (0 non-empty), 21 shared-memory (19 non-empty)), cost = 1215.4, running time = 34s
We may design a more fine-grained cost function to make better use of this.
=> [simulation] Consider the cost of attaching single-qubit gates

src/quartz/circuitseq/circuitgate.cpp, src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/gate/all_gates.h, src/quartz/gate/gate.cpp, src/quartz/gate/gate.h, src/quartz/gate/gates.inc.h, src/quartz/gate/general_controlled_gate.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
Related issue = #105
This PR adds general controlled gates and outputs them in the simulation schedule. It takes into consideration all `X` gates, and changes the control state of controlled gates whenever necessary. For example,
```
CZ[0](Q1, Q2)
```
means to apply a `Z` gate to `Q2` when `Q1` is |0> instead of |1>.
This PR does not support handling the removal of `CX` gates but it prints a warning message whenever a `CX` gate is removed.
Other changes:
- Fixes a bug introduced in #102 which may cause the same qubit to appear in an open fusion kernel's active qubits and an absorbing shared-memory kernel's touching qubits at the same time. This did not cause problems in previous experiments.
Benchmark: exactly the same as #104.
=> [simulator] Use general controlled gates in simulation schedule and fix a bug

src/quartz/generator/generator.cpp, src/quartz/generator/generator.h
This PR supports (possibly parametrized) 3-qubit gates in the `bfs` method of `generator`. 
It also makes `generator` no longer search for permutations of symmetric gates (e.g., `CZ(Q0, Q1)` and `CZ(Q1, Q0)` are no longer both generated -- only the first one is kept). @zikun-li feel free to tell me if you want to revert this change.
=> [Generator] Support 3-qubit gates in ECC set generation

config/config.linux, src/sim/examples/legion-based/CMakeLists.txt, src/sim/examples/legion-based/test_sim_legion.cc, src/sim/include/const.h, src/sim/include/distributed_simulator.h, src/sim/include/simgate.h, src/sim/src/offload/distributed_simulator.cc, src/sim/src/offload/distributed_simulator.cu
Legion-based offload version is tested on single device for 28-qubit (24 local) dj circuit.
To FIX: we cannot `malloc` for more memory to store the gates info to pass to the tasks. It seems that there will be some memory corruption. Need to check if Legion has any restrictions on this.
The shm kernels are not tested in this PR.
=> [legion] single-device 28-qubits dj tested (no shm)

src/quartz/simulator/schedule.cpp, src/test/test_simulation.cpp
There is one case that is missed when postponing attaching single-qubit gates to multi-qubit gates as far as possible in #100: if there is a multi-qubit gate with exactly one local qubit in the current stage but at least one of the global qubits will become local in the next stage, then we must attach the gate in this stage. This PR implements this case.
This PR also updates `test_simulation` to the new cost function and also adds some debug assertions.
Benchmark: qft circuit, 33 total qubits, 28 total qubits, with the new cost function:
Before (wrong): 14 fusion, 3 shared-memory, total cost = 256 + 25.4 = 281.4, running time = 12s
After: 14 fusion, 3 shared-memory, total cost = 268.5 + 25.4 = 293.9, running time = 13s
If we remove all `SWAP` gates: total cost = 7 fusion (2 empty), 4 …
=> [simulation] Fix a bug which may have caused multi-qubit gates to be attached

src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
This PR removes empty kernels and schedules generated in `get_schedules()`.
It also restricts the warning about attaching CX and CXX gates to be printed at most once.
=> [simulation] Remove empty kernels and schedules

src/quartz/tasograph/substitution.cpp
Calling `erase (map.end())` is undefined behavior, and was segfaulting for me.
=> fix segfault

src/quartz/tasograph/substitution.cpp, src/quartz/tasograph/tasograph.cpp
It is my attempt to fix the issue #124, which was possibly introduced by PR #123. @zikun-li, can you please check? 
In an unrelated change, I also edited a line in `substitution.cpp` that was tripping earlier.
=> fix issue of reading params

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/parser/qasm_parser.h, src/quartz/tasograph/tasograph.cpp
A follow-up from https://github.com/quantum-compiler/quartz/pull/125#issuecomment-1542549883.
I think this can serve as a first step to move the control of all parameters from `CircuitSeq` to `Context`. This might need a more careful design for `Context` though.
=> [refactor] Let Context know which input parameters are symbolic

env.yml, python/requirements.txt, python/setup.py
Previously env.yml automatically chose the latest Qiskit version. On Oct 4, 2023, Qiskit-terra released v0.25.2.1 (Qiskit v0.44.0), which required `symengine < 0.10`. While symengine v0.10 fixed a bug in #110, previous CI used symengine v0.9.2, and the line `symengine < 0.10` existed in Qiskit-terra since March, so this is probably not the exact reason why CI failed.
After several tries, fixing Python to any minor version of 3.11 (i.e., < 3.12) seems to solve this issue. It seems that symengine does not support Python 3.12 yet (https://github.com/symengine/symengine-wheels/issues/11, https://github.com/Qiskit/qiskit/issues/10887).
=> [CI] Fix incompatible Python version with symengine

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/test/test_simulation.cpp
Global changes:
- Add `CircuitSeq::random_gate_permutation()` to randomly select a valid topological order as the sequence.
- Improve some comments.
Changes specific to the simulator:
- Use `std::unique_ptr` for `CircuitSeq` in `Schedule`
Benchmark: qft, 33 qubits, 28 local qubits:
Before:
```
2 stages.
Kernel info: 11 kernels (8 fusion, 3 shared-memory), cost = 271.5, local qubits 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
Kernel info: 4 kernels (4 fusion, 0 shared-memory), cost = 25.4, local qubits 5 6 7 8 9 10 11 12 13 28 29 30 31 32 19 20 21 22 23 24 25 26 27 0 1 2 3 4
0 seconds.
```
After (20 random permutations for each stage, taking ~5 seconds to run in total):
```
Kernel info: 16 kernels (11 fusion, 5 shared-memory), cost = 304.2, local qubits 5 …
```
=> [Simulator] Randomly permute gates before the simple DP

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/simulator/schedule.cpp, src/test/test_simulation.cpp
Changes specific to the simulator:
I use the following heuristic to permute the gates before the simple DP:
- Each qubit is assigned a cumulative **weight**, initially 0.
- When doing topological sort, invoke a gate chooser each time we choose a gate (even if there is only one choice), so there are guaranteed to be `num_gates` iterations.
- In each iteration:
- Compute the *weight* of each gate to be the average of the **weight** of each qubit.
- Choose a gate with probability proportional to *exp(weight)*.
- Multiply the **weight** of each qubit by 0.9. (Discounting old weights.)
- For each qubit `q` the gate operates on, increase the **weight** of each other qubit `j` by `pow(0.5, abs(j - q))`, i.e., `weight[q] += 1, weight[q - 1] += 0.5, weight[q + 1] += 0.5, weight[q - 2] += 0.25, …
=> [Simulation] A better heuristic for permuting gates before the simple DP

src/benchmark/CMakeLists.txt, src/benchmark/dp.cpp, src/quartz/simulator/schedule.cpp
- Add a benchmark file for the simple DP (run only on the original sequence, only use the max weight, randomized with 10 or 100 runs) to compare with the complicated DP 
- Add a temporary flag (`repeat = -1`) to only use the max weight in `gate_chooser`
- Remove the assertion that the circuit must be entangled in the complicated DP
=> [Simulator] A benchmark for the simple DP

src/benchmark/dp.cpp, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/test/test_remove_swap.cpp
Previously the simple DP had both time and space complexity O(n^2) where n is the number of gates. This PR reduces the space complexity to O(n) by doing the DP in reversed order.
Also removed the randomized part in benchmark_dp and added some code for NWQBench.
=> [Simulator] Do the simple DP in reversed order and update the benchmark for DP

src/benchmark/dp.cpp, src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/simulator/kernel.cpp, src/quartz/simulator/kernel.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/quartz/utils/string_utils.h, src/quartz/utils/utils.h, src/test/test_simulation.cpp
- Cache the kernel schedules to avoid running DP multiple times for an unchanged circuit, adding functions `Schedule::from_file` and `Schedule::save_to_file` (`benchmark_dp` now caches the schedules)
- Add a function to run ILP and DP together to also avoid running ILP multiple times (`test_simulation` now calls this)
- Add functions `Kernel::to_qasm_style_string` and `Kernel::from_qasm_style_string` to serialize/deserialize kernels
- Wrap `Kernel::gates` with `std::unique_ptr` for better memory management
Changes in general parts:
- Add functions `CircuitSeq::to_qasm_style_string` and `CircuitSeq::from_qasm_style_string` to serialize/deserialize from QASM-style strings in addition to QASM files
- If a parameter is 0, output `0` instead of `0.000000000000000` …
=> [Simulator] Cache the kernel schedules

src/quartz/circuitseq/circuitgate.cpp, src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/math/vector.cpp, src/quartz/parser/qasm_parser.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h, src/test/test_simulation.cpp
- Add a function to verify the correctness of a schedule by random testing
- Preserve the order of single-qubit gates when attaching them to multi-qubit gates in the DP (bug fix)
Changes in general parts:
- Support printing gates (`CircuitGate::to_string()`) for any number of qubits (previously only supported <= 2 qubits)
- Add a comment `//ctrl` when printing circuits for restoring generalized controlled gates in the future
- Add a function `Context::get_all_param_values()` to get all input parameter values
- Add an assertion `num_qubits <= 30` in vector.cpp to avoid integer overflow
=> [Simulator] Verify schedule for small circuits and preserve order when attaching gates

src/quartz/parser/qasm_parser.h
Close #105
Now we can read and write general controlled gates.
In OpenQASM 2 (the format we write to and read from):
```qasm
//ctrl
x q[5];
ccz q[5],q[6],q[8];
x q[5];
```
In `CircuitSeq::to_string()`:
```
[Q5, Q6, Q8] = ccz[01](Q5, Q6, Q8)
```
OpenQASM 3 equivalent _(not supported)_:
```qasm
negctrl @ ctrl @ z q[5],q[6],q[8];
```
Compare with common controlled gates:
In OpenQASM 2 (the format we write to and read from):
```qasm
ccz q[5],q[6],q[8];
```
In `CircuitSeq::to_string()`:
```
[Q5, Q6, Q8] = ccz(Q5, Q6, Q8)
```
OpenQASM 3 equivalent _(not supported)_:
```qasm
ctrl(2) @ z q[5],q[6],q[8];
```
=> [gate] Support parsing general controlled gates

src/benchmark/dp.cpp, src/quartz/simulator/schedule.cpp
- Disable attaching CX/CCX gates to other gates (so we should not see warnings about them)
- Fix a bug causing infeasible shared-memory kernels in reversed simple DP
- Minor fixes to compiler warnings
=> [simulator] Disable attaching CX gates and fix a bug in reversed simple DP

src/benchmark/dp.cpp, src/python/simulator/ilp.py, src/quartz/pybind/pybind.cpp, src/quartz/pybind/pybind.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
Related PR = #147 
This PR changes
```C++
std::vector<std::vector<int>>
compute_qubit_layout_with_ilp(const CircuitSeq &sequence, int num_local_qubits,
int num_regional_qubits, Context *ctx,
PythonInterpreter *interpreter,
int num_global_stages_start_with = 1);
```
and
```C++
std::vector<Schedule> get_schedules_with_ilp(
const CircuitSeq &sequence, int num_local_qubits, int num_regional_qubits,
const KernelCost &kernel_cost, Context *ctx, PythonInterpreter *interpreter,
bool attach_single_qubit_gates, int use_simple_dp_times = 0,
const std::string &cache_file_name_prefix = "", int answer_start_with = 1);
```
to use a new ILP algorithm. Now the local qubit swap pairs should not intersect with each other and the number of stages is minimized.
Also prints the local qubit swap information in …
=> [Simulator] A new ILP algorithm

src/benchmark/dp.cpp, src/quartz/gate/general_controlled_gate.h, src/quartz/simulator/kernel.cpp, src/quartz/simulator/kernel.h, src/quartz/simulator/schedule.cpp, src/quartz/simulator/schedule.h
- Track which qubits are local in the simple DP, do not add non-local qubits to kernels
- Verify the schedule to be executable in benchmark_dp
- Added more data points in benchmark_dp
Changes in general:
- Generalized controlled gates now take the underlying controlled gate's `is_symmetric()` and `is_diagonal()` directly. I believe changing control indices will not affect these two properties.
=> [Simulator] Consider which qubits are local in simple DP and verify the schedule

src/quartz/simulator/schedule.cpp, src/test/test_simulation.cpp
When we attach single-qubit gates to previous stages, we must make sure that they are still "single-qubit" in these stages. This PR fixes the bug of attaching gates that are single-qubit in this stage but multi-qubit in some previous stages because some global qubits are local in the previous stage.
=> [simulator] Fix a bug of attaching to previous stages incorrectly

src/quartz/tasograph/tasograph.cpp
Closes #153 
This PR uses the gate type instead of pointers so that we can compare different graphs generated in different contexts using the hash value.
=> [optimizer] Use gate type instead of pointers when computing the hash value for graphs

src/quartz/gate/gate.cpp, src/quartz/gate/gate.h
This PR can help with debugging when `Gate` objects are mistakenly instantiated.
Also makes `Gate::is_toffoli_gate()` more systematic.
=> [gate] Add warnings when the base get_matrix() is called

src/quartz/dataset/equivalence_set.cpp, src/quartz/dataset/equivalence_set.h
#159 enables more systematic parameter-related pruning on the ECC Set.
This PR does the following two prunings:
1. If an ECC does not use a prefix of the input symbolic parameters, e.g., uses P1 but not P0 (they are both input symbolic parameters), remove this ECC because the complete ECC Set should have an ECC that is replacing each occurrence of P1 with P0 in this ECC.
2. If an ECC uses one input symbolic parameter only in one non-trivial expression, e.g., uses P1+P2 but neither P2 nor any other expression containing P2, remove this ECC because the complete ECC Set should have an ECC that is replacing each occurrence of P1+P2 with P2 in this ECC.
(These two prunings are implemented assuming there are no more than 63 input symbolic parameters, and they have the smallest indices in [0, …
=> [Generator] Parameter-related pruning on ECC Set

src/quartz/circuitseq/circuitseq.cpp, src/test/test_optimize.cpp
Fix a bug caused by the Json format change in #159 and also a place missing the parameter specification when constructing the context.
=> [bug] Fix test_optimize and CircuitSeq::read_json

src/benchmark/nam_middle_circuits.cpp, src/benchmark/nam_small_circuits.cpp, src/quartz/context/context.cpp, src/quartz/parser/qasm_parser.h, src/quartz/tasograph/substitution.cpp, src/quartz/tasograph/substitution.h, src/quartz/tasograph/tasograph.cpp, src/test/test_generator.cpp, src/test/test_ibmq.cpp, src/test/test_ibmq_td_disabled.cpp, src/test/test_nam.cpp, src/test/test_nam_td_disabled.cpp, src/test/test_quartz.cpp, src/test/test_rigetti.cpp, src/test/test_rigetti_td_disabled.cpp
Now each `GraphXfer` object stores `src_ctx, dst_ctx, union_ctx` so that it can transform a circuit from one context to another.
This PR also allows each parameter to be used multiple times in rotation merging.
It also removes some debug outputs introduced in previous PRs.
=> [bug] Shift the context when applying xfers

src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h
So that we can set timeout values that are not multiples of 1s.
Also removes an incorrect `// namespace quartz` comment.
=> [Optimizer] Change the timeout type from int to double

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/dataset/dataset.cpp, src/quartz/dataset/dataset.h, src/quartz/generator/generator.cpp, src/quartz/utils/utils.h, src/quartz/verifier/verifier.cpp, src/test/gen_ecc_set.cpp, src/test/gen_ecc_set.h
This PR implements comparison by row representation in RepGen.
It also allows running RepGen and `gen_ecc_set.cpp` from any directory (not necessarily from `quartz/` or `build/` now).
Please change
```C++
constexpr bool kUseRowRepresentationToCompare = true;
```
to
```C++
constexpr bool kUseRowRepresentationToCompare = false;
```
in `utils/utils.h` if you want to use the previous RepGen version.
=> [Generator] Use row representation in RepGen

src/quartz/utils/utils.h
Revert the row representation change in #173.
Will turn it on when there is evidence that the row representation is better.
=> [Generator] Switch back to the previous canonical representation version

src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitgate.h, src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/generator/generator.cpp, src/quartz/utils/utils.h, src/quartz/verifier/verifier.cpp, src/quartz/verifier/verifier.h, src/test/gen_ecc_set.cpp, src/test/gen_ecc_set.h, src/test/test_optimization_steps.cpp
This PR adds a function to verify circuit transformations. It first removes the common first/last gates from each circuit transformation step, then uses Z3 to verify if the remaining parts are equivalent. If the hash values differ by more than 1, it will not invoke Z3 and report they are not equivalent directly. Assuming the code is implemented correctly, it guarantees that the two circuits are equivalent if it returns true.
Example potential output of `test_optimization_steps`:
```
...
Verifying circuit 4 -> circuit 5
Checking Verifier::equivalent() on:
CircuitSeq {
0: Q0 = t(Q0)
1: Q0 = tdg(Q0)
}
CircuitSeq {
}
Considering a total of 2 circuits split into 1 hash values...
Processed 0 hash values that had only 1 circuit sequence, now processing the remaining 1 ones with 2 or more circuit …
```
=> [Verifier] Verify each circuit transformation step

src/quartz/tasograph/tasograph.cpp
Some parameters may not have a range [0, 2pi). We should not normalize them.
We still normalize to [0, 2pi) in rotation merging. We may need to fix further if a parameter expression is involved in both rotation merging and another gate with the parameter range not [0, 2pi).
=> [Optimizer] Do not modulo 2pi at circuit input

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/test/test_pi.cpp, src/test/test_qasm_parser.cpp
**Summary**
This pull request allows parsing of OpenQASM 3 qubit declarations.
**Details**
In OpenQASM 2, a qubit array is declared using the `qreg name[len];` statement, whereas in OpenQASM 3 the statement `qubit[len] name` is preferred. This pull request extends the `QASMParser` to support the `qubit` command.
**Main Changes**
- Every `[` symbol in each command is prefixed by a space. This ensures that the `qubit` in `qubit[len]` is disconnected from the designator `[len]`.
- The qreg parsing code has been factored out into `QubitParser`.
- The `QASMParser` supports OpenQASM 3 qubit declarations.
=> Parser support for qasm3 qubits.

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/test/test_qasm_parser.cpp
**Summary**
This pull request makes the minimal amount of changes to soundly and efficiently support parameters across multiple files.
**Details**
The current `QasmParser` does not handle multiple files well when it comes to symbolic parameters. In terms of soundness, there is no way to tell the parser that common symbolic parameters across multiple files are the same parameter. Moreover, when parsing multiple files, there will be gaps between the symbolic parameters (assuming any expressions or constant parameters are used).
This commit fixes these issues by making the `ParamParser` a member variable of `QasmParser` (so that parameters are not forgotten between files), and by allowing parameters from the first file to be reused in subsequent files. The workflow proceeds as follows.
1. …
=> [Parser] Parsing multiple files with symbolic parameters

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/test/test_qasm_parser.cpp
**Summary**
Allows for expressions with binary (+) and (-).
**Details**
The current version of `ParamParser` assumes that each expression is a single term. This term is either a multiple of pi, a literal value, or the name of a parameter variable. However, it is not possible to add or subtract terms in a single expression. On the other hand, many tools (such as `dumps(circ)` in qiskit) generate OpenQASM files with expressions consisting of two or more terms. These terms often mix constants with parameter variables.
The pull request adds simple support for multi-term expressions. The parser assumes that each expression is of the form `t` , `-t` , `e+t`,  and `e-t` , where `e` is an expression and `t` is a term. This inductive definition is relatively easy to parse, and should support the …
=> Support for expressions made from multiple terms.

src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/context/param_info.cpp, src/quartz/context/param_info.h, src/quartz/gate/gate.cpp, src/quartz/gate/gate.h, src/quartz/gate/rx.h, src/quartz/gate/ry.h, src/quartz/gate/rz.h, src/quartz/gate/u3.h, src/test/gen_ecc_set.h, src/test/test_all.cpp, src/test/test_bfs.cpp, src/test/test_constants.cpp, src/test/test_generator.cpp, src/test/test_generator.h, src/test/test_mult.cpp, src/test/test_optimize.cpp, src/test/test_phase_shift.cpp, src/test/test_pi.cpp, src/test/test_pruning.h, src/test/test_qasm_parser.cpp, src/test/test_sparsity.cpp
**Summary**
This pull request introduces a flag for each parameter, which identifies whether it is halved or not. A halved parameter is a symbolic parameter that can be used in gates which take parameters of the form $\theta / 2$. Examples of such gates include `rx`, `ry`, and `rz`.
**Details**
This pull request makes two changes to Quartz. First, each gate now has an `is_param_halved(i)` method, which returns true if parameter `i` is of the form $\theta / 2$. The parameter index is taken an argument, since gates such as `u3` have both halved parameters and standard parameters.
This new metadata is then used by the `Context` to determine if any halved parameter gates are in use. If such a gate is in use, then the context conservatively assumes that the parameter will appear in a halved …
=> [Context] Halved parameter flag.

src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitseq.cpp, src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/test/test_qasm_parser.cpp
**Summary**
This pull request extends the OpenQASM parser and code generator to support halved parameters.
**Related Issues**
This pull request should resolve issue #190.
**Details**
To parse gates with halved parameters, the following three changes are made to `QasmParser`.
- If a halved symbolic parameter `p[i]` is used in a context where parameters are not halved, then the parameter is scaled by `2`. Formally, it is replaced by `p[i] + p[i]`.
- If a standard symbolic parameter is used in a context where parameters are halved, then an error is raised.
- If a constant parameter is used in a context where parameters are halved, then the parameter is scaled by `1/2`.
To print gates with halved parameters, `to_qasm_style_string` now scales constant halved parameters by a factor of `2`. …
=> Parser support for halved parameters.

src/quartz/tasograph/substitution.cpp, src/quartz/tasograph/substitution.h, src/quartz/tasograph/tasograph.cpp, src/quartz/tasograph/tasograph.h
Add comments for pattern matching, fix typos, fix some clang-tidy code format
=> [doc] Update comments for pattern matching

src/python/verifier/verifier.py
Timeout should be the 9th positional argument for `equivalent` but it is being passed as the 8th positional argument in several places.
=> [fix] verifier passes timeout in wrong position

src/python/verifier/gates.py, src/python/verifier/verifier.py
It seems that defining a variable works much better than `z3.Sqrt` (which returns a root object).
See also: https://stackoverflow.com/questions/30328888/use-z3-and-smt-lib-to-define-sqrt-function-with-a-real-number
=> [verifier] Improve reasoning about constant square roots in Z3

src/quartz/circuitseq/circuitseq.cpp, src/quartz/verifier/verifier.cpp
This PR fixes a bug in #176.
Before this PR, the common parts of two circuits may not be removed correctly. It was possible that one gate was removed in the first circuit but left in the second circuit, causing the verifier to be unable to verify. I did assert that the numbers of gates removed for both circuits were the same, but the assertion was not triggered in release mode.
=> [bug] [verifier] Fix a bug when finding common subcircuits

src/python/verifier/verifier.py
In the verifier, all parameters `theta` are stored in the `cos(theta), sin(theta)` format. This PR aligns concrete parameters with this format so that some other functions work properly.
=> [verifier] Use trigonometric functions for concrete parameters

src/python/verifier/verifier.py, src/quartz/circuitseq/circuitgate.cpp, src/quartz/circuitseq/circuitseq.cpp, src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/context/param_info.cpp, src/quartz/context/param_info.h, src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h, src/quartz/tasograph/tasograph.cpp
#203 fixes concrete parameters in the verifier, but causes troubles for symbolic constant expressions like `pi / 2` in the verifier. This PR introduces an enum-like class (but not an enum class so as to allow for member functions) `ParamClass`, and prints [parameters only for arithmetic expressions] as an **integer** while printing [concrete parameters] as **floating-point values**.
=> [Verifier] Distinguish parameters only for arithmetic expressions from concrete parameters which uses trigonometric functions

src/benchmark/CMakeLists.txt, src/benchmark/benchmark_optimization_steps.cpp, src/quartz/tasograph/substitution.cpp, src/quartz/tasograph/substitution.h, src/quartz/tasograph/tasograph.cpp, src/test/test_optimization_steps.cpp, src/test/test_optimization_steps.h
Also extracts the code to get all transformations from an ECC set to a separate function. Note that `EquivalenceSet::load_json` clears existing parameters in the `ParamInfo` object, it's better to load the transformations at the beginning to avoid clearing parameters if the `ParamInfo` is reused later.
=> [optimizer] Add a benchmark for optimization steps

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h
If two OpenQASM files contain the same concrete constant parameters like `pi*0.125`, the parser will now reuse the same parameter.
=> [Parser] Let parameter parser reuse the same concrete constant parameters across files

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/verifier/verifier.cpp
This PR removes unused qubits when verifying transformation steps, so that we don't need to create 2^40 variables in the verifier if the circuit contains 40 qubits but only 2 or 3 qubits are used.
This PR also lets `CircuitSeq::get_permuted_seq` support reducing the number of qubits when cloning (requiring that qubits not cloned are unused), and fixes a potential bug that may cause `CircuitSeq::outputs` to be not in the correct order when qubits are permuted.
=> [verifier] Remove unused qubits when verifying transformation steps

src/benchmark/benchmark_optimization_steps.cpp, src/quartz/dataset/dataset.cpp, src/quartz/dataset/dataset.h, src/quartz/verifier/verifier.cpp, src/test/test_optimization_steps.h
This PR fixes a bug in `Verifier::equivalent` when removing common prefix gates, that if the first circuit is a prefix of the second circuit, this function would also remove the entire second circuit before this PR. After this PR, this function will correctly keep the remaining part of the second circuit.
This PR also avoids generating the hashing distribution in `test_optimization_steps.h`. The hashing distribution is only for `CircuitSeq::hash()`, and it takes up space of Theta(2^num_qubits). This size is huge when the number of qubits is greater than 30. We can test circuits with more than 30 qubits after this PR.
Also adds some debugging output when `verbose` is true.
=> [verifier] [bug] Fix a bug when removing common prefix gates and do not generate hashing distribution in test_optimization_steps.h

src/quartz/circuitseq/circuitseq.cpp, src/quartz/circuitseq/circuitseq.h, src/quartz/verifier/verifier.cpp
This algorithm is cleaner than using gates as a frontier.
=> [verifier] Use qubit wires instead of gates as a frontier when removing common prefix gates

src/python/verifier/gates.py, src/test/test_pi.py
This PR adds a solver to bound the values of expressions using variables `sqrt2, sqrt3, sqrt5, sqrt_of_5_minus_sqrt5`, so that in the half-angle formula, we know if the value is non-negative or non-positive in some cases. In these cases, we can flatten the if-expression to reduce the burden of Z3.
=> [verifier] Flatten if-expression in half-angle formula using sqrt2,3,5

src/quartz/circuitseq/circuitgate.cpp, src/quartz/context/context.cpp, src/quartz/context/context.h, src/quartz/context/param_info.cpp, src/quartz/context/param_info.h, src/test/test_pi.cpp
Close #201 
This PR prints out `pi` symbolically if it is stored symbolically in Quartz.
Example in `test_pi`:
```c++
ParamInfo param_info;
Context ctx({GateType::rx, GateType::pi}, 1, &param_info);
auto p1 = ctx.get_new_arithmetic_param_id(2);
auto p2 = ctx.get_new_param_expression_id({p1}, ctx.get_gate(GateType::pi));
CircuitSeq dag2(1);
dag2.add_gate({0}, {p2}, ctx.get_gate(GateType::rx), &ctx);
std::cout << dag2.to_qasm_style_string(&ctx) << std::endl;
```
Result: 
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
rx(2*pi/2) q[0];
```
The `2*pi/2` is due to an artifact that caused us to divide the parameter by 2 and then multiply it by 2.
The JSON file format used by the verifier is not affected by this PR.
=> [QASM] Print out pi symbolically if possible

src/quartz/parser/qasm_parser.cpp, src/quartz/parser/qasm_parser.h
Before this PR, `seq` is still a `nullptr` after calling the parser if the circuit has no gates. This PR fixes this issue by creating an empty circuit.
=> [Parser] Fix parser crashing on circuits with no gates
